const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const fs = require('fs');

const dbPath = path.join(__dirname, '../../data/learning.db');
const dataDir = path.dirname(dbPath);

if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
}

const db = new sqlite3.Database(dbPath);

const words = [
    { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃，抛弃', example: 'She decided to abandon her career and travel the world.', category: '高频' },
    { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力，才能', example: 'His ability to solve problems is impressive.', category: '高频' },
    { word: 'absolute', phonetic: '/ˈæbsəluːt/', meaning: 'adj. 绝对的，完全的', example: 'I have absolute confidence in you.', category: '高频' },
    { word: 'absorb', phonetic: '/əbˈzɔːrb/', meaning: 'v. 吸收，吸引', example: 'Plants absorb sunlight for photosynthesis.', category: '高频' },
    { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的; n. 摘要', example: 'The concept of justice is abstract.', category: '中频' },
    { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: 'adj. 学术的; n. 学者', example: 'She has a strong academic background.', category: '高频' },
    { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速，促进', example: 'Economic growth accelerated this year.', category: '中频' },
    { word: 'accept', phonetic: '/əkˈsept/', meaning: 'v. 接受，认可', example: 'I accept your apology.', category: '高频' },
    { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道; v. 访问', example: 'You need a password to access this file.', category: '高频' },
    { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴，伴随', example: 'The text is accompanied by illustrations.', category: '中频' },
    { word: 'accomplish', phonetic: '/əˈkɑːmplɪʃ/', meaning: 'v. 完成，实现', example: 'We accomplished our goal ahead of schedule.', category: '中频' },
    { word: 'according', phonetic: '/əˈkɔːrdɪŋ/', meaning: 'prep. 根据，按照', example: 'According to the report, sales increased.', category: '高频' },
    { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户; 描述; v. 解释', example: 'He gave a detailed account of the incident.', category: '高频' },
    { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: 'v. 积累，积聚', example: 'Dust accumulates on the surface.', category: '中频' },
    { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 精确的，准确的', example: 'The data is accurate.', category: '高频' },
    { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现，达到', example: 'She achieved excellent results.', category: '高频' },
    { word: 'acknowledge', phonetic: '/əkˈnɑːlɪdʒ/', meaning: 'v. 承认；致谢', example: 'He acknowledged his mistake.', category: '中频' },
    { word: 'acquire', phonetic: '/əˈkwaɪər/', meaning: 'v. 获得，学到', example: 'She acquired a good knowledge of English.', category: '高频' },
    { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编', example: 'We must adapt to changing conditions.', category: '高频' },
    { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的，适当的', example: 'The supply is adequate for our needs.', category: '高频' },
    { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整，调节', example: 'Please adjust the temperature.', category: '高频' },
    { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: 'n. 管理；行政', example: 'She works in public administration.', category: '中频' },
    { word: 'admire', phonetic: '/ədˈmaɪər/', meaning: 'v. 钦佩，赞赏', example: 'I admire your courage.', category: '中频' },
    { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认；准许进入', example: 'He admitted his mistake.', category: '高频' },
    { word: 'adopt', phonetic: '/əˈdɑːpt/', meaning: 'v. 采用；收养', example: 'The committee adopted the proposal.', category: '高频' },
    { word: 'advance', phonetic: '/ədˈvæns/', meaning: 'v. 前进；提前', example: 'Technology has advanced rapidly.', category: '高频' },
    { word: 'advantage', phonetic: '/ədˈvæntɪdʒ/', meaning: 'n. 优势，好处', example: 'This gives us a competitive advantage.', category: '高频' },
    { word: 'advertise', phonetic: '/ˈædvərtaɪz/', meaning: 'v. 做广告', example: 'They advertise their products online.', category: '中频' },
    { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响；感动', example: 'The climate affects agriculture.', category: '高频' },
    { word: 'afford', phonetic: '/əˈfɔːrd/', meaning: 'v. 负担得起', example: 'I can afford the expense.', category: '高频' },
    { word: 'agenda', phonetic: '/əˈdʒendə/', meaning: 'n. 议程', example: 'What is on the agenda today?', category: '中频' },
    { word: 'aggressive', phonetic: '/əˈɡresɪv/', meaning: 'adj. 侵略的；积极的', example: 'Aggressive marketing boosted sales.', category: '中频' },
    { word: 'agree', phonetic: '/əˈɡriː/', meaning: 'v. 同意', example: 'I agree with your opinion.', category: '高频' },
    { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', meaning: 'n. 农业', example: 'Agriculture is vital for the economy.', category: '中频' },
    { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: 'v. 分配', example: 'Funds were allocated for education.', category: '中频' },
    { word: 'allow', phonetic: '/əˈlaʊ/', meaning: 'v. 允许', example: 'Smoking is not allowed here.', category: '高频' },
    { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', meaning: 'adj. 替代的; n. 选择', example: 'We have no alternative but to wait.', category: '高频' },
    { word: 'amaze', phonetic: '/əˈmeɪz/', meaning: 'v. 使惊奇', example: 'Your progress amazes me.', category: '中频' },
    { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心，抱负', example: 'She has great ambition.', category: '中频' },
    { word: 'analyze', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析', example: 'We need to analyze the data.', category: '高频' },
    { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布', example: 'They announced the results.', category: '高频' },
    { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 年度的', example: 'The annual report is published.', category: '高频' },
    { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', meaning: 'n. 焦虑', example: 'He felt anxiety before the exam.', category: '中频' },
    { word: 'apparent', phonetic: '/əˈpærənt/', meaning: 'adj. 明显的', example: 'It became apparent that he was lying.', category: '中频' },
    { word: 'appeal', phonetic: '/əˈpiːl/', meaning: 'n./v. 呼吁；吸引', example: 'The idea appeals to young people.', category: '中频' },
    { word: 'appear', phonetic: '/əˈpɪr/', meaning: 'v. 出现；似乎', example: 'She appeared to be sleeping.', category: '高频' },
    { word: 'apply', phonetic: '/əˈplaɪ/', meaning: 'v. 应用；申请', example: 'Apply the theory to practice.', category: '高频' },
    { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: 'v. 欣赏；感激', example: 'I appreciate your help.', category: '高频' },
    { word: 'approach', phonetic: '/əˈproʊtʃ/', meaning: 'v. 接近; n. 方法', example: 'A new approach is needed.', category: '高频' },
    { word: 'appropriate', phonetic: '/əˈproʊpriət/', meaning: 'adj. 适当的', example: 'Choose an appropriate method.', category: '高频' },
    { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准；赞成', example: 'The plan was approved.', category: '高频' },
    { word: 'argue', phonetic: '/ˈɑːrɡjuː/', meaning: 'v. 争论；论证', example: 'Scholars argue about the cause.', category: '高频' },
    { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现；产生', example: 'Problems arise from poor planning.', category: '中频' },
    { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排；整理', example: 'We arranged a meeting.', category: '中频' },
    { word: 'article', phonetic: '/ˈɑːrtɪkl/', meaning: 'n. 文章；物品', example: 'She wrote an article on climate change.', category: '高频' },
    { word: 'aspect', phonetic: '/ˈæspekt/', meaning: 'n. 方面', example: 'Consider every aspect of the problem.', category: '高频' },
    { word: 'assess', phonetic: '/əˈses/', meaning: 'v. 评估', example: 'We need to assess the damage.', category: '高频' },
    { word: 'assign', phonetic: '/əˈsaɪn/', meaning: 'v. 分配；指派', example: 'They assigned him the task.', category: '中频' },
    { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 帮助，协助', example: 'Can you assist me with this?', category: '中频' },
    { word: 'associate', phonetic: '/əˈsoʊʃieɪt/', meaning: 'v. 联想；交往', example: 'We associate Egypt with pyramids.', category: '高频' },
    { word: 'assume', phonetic: '/əˈsuːm/', meaning: 'v. 假设；承担', example: 'I assume you are right.', category: '高频' },
    { word: 'atmosphere', phonetic: '/ˈætməsfɪr/', meaning: 'n. 大气；氛围', example: 'The atmosphere was tense.', category: '中频' },
    { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附上；依恋', example: 'Please attach the file.', category: '中频' },
    { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'n./v. 尝试', example: 'She made an attempt to escape.', category: '高频' },
    { word: 'attend', phonetic: '/əˈtend/', meaning: 'v. 参加；照顾', example: 'All students must attend class.', category: '高频' },
    { word: 'attitude', phonetic: '/ˈætɪtuːd/', meaning: 'n. 态度', example: 'She has a positive attitude.', category: '高频' },
    { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引', example: 'The museum attracts many visitors.', category: '高频' },
    { word: 'authority', phonetic: '/əˈθɔːrəti/', meaning: 'n. 权威；当局', example: 'The local authority made the decision.', category: '高频' },
    { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的', example: 'The product is now available.', category: '高频' },
    { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'adj. 平均的; n. 平均数', example: 'The average temperature is rising.', category: '高频' },
    { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免', example: 'Try to avoid mistakes.', category: '高频' },
    { word: 'aware', phonetic: '/əˈwer/', meaning: 'adj. 意识到的', example: 'Are you aware of the risks?', category: '高频' },
    { word: 'balance', phonetic: '/ˈbæləns/', meaning: 'n. 平衡; v. 使平衡', example: 'Keep a balance between work and life.', category: '高频' },
    { word: 'barrier', phonetic: '/ˈbæriər/', meaning: 'n. 障碍', example: 'Language can be a barrier.', category: '中频' },
    { word: 'behave', phonetic: '/bɪˈheɪv/', meaning: 'v. 行为；表现', example: 'Children should behave well.', category: '中频' },
    { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: 'n. 利益; v. 受益', example: 'Exercise benefits your health.', category: '高频' },
    { word: 'blame', phonetic: '/bleɪm/', meaning: 'v. 责备; n. 责任', example: 'Don\'t blame others.', category: '中频' },
    { word: 'budget', phonetic: '/ˈbʌdʒɪt/', meaning: 'n. 预算', example: 'We need to stay within budget.', category: '中频' },
    { word: 'calculate', phonetic: '/ˈkælkjuleɪt/', meaning: 'v. 计算', example: 'Calculate the total cost.', category: '中频' },
    { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'n. 运动；战役', example: 'They launched a marketing campaign.', category: '中频' },
    { word: 'capable', phonetic: '/ˈkeɪpəbl/', meaning: 'adj. 有能力的', example: 'She is capable of great things.', category: '高频' },
    { word: 'capacity', phonetic: '/kəˈpæsəti/', meaning: 'n. 容量；能力', example: 'The hall has a seating capacity of 500.', category: '中频' },
    { word: 'capture', phonetic: '/ˈkæptʃər/', meaning: 'v. 捕获；记录', example: 'The photo captured a beautiful moment.', category: '中频' },
    { word: 'career', phonetic: '/kəˈrɪr/', meaning: 'n. 职业，生涯', example: 'She has a successful career.', category: '高频' },
    { word: 'category', phonetic: '/ˈkætəɡɔːri/', meaning: 'n. 类别', example: 'Divide them into categories.', category: '中频' },
    { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: 'v. 庆祝', example: 'We celebrated her birthday.', category: '中频' },
    { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: 'n. 挑战; v. 质疑', example: 'Learning English is a challenge.', category: '高频' },
    { word: 'character', phonetic: '/ˈkærəktər/', meaning: 'n. 性格；角色', example: 'He is a man of strong character.', category: '高频' },
    { word: 'circumstance', phonetic: '/ˈsɜːrkəmstæns/', meaning: 'n. 环境；情况', example: 'Under the circumstances, we must wait.', category: '中频' },
    { word: 'claim', phonetic: '/kleɪm/', meaning: 'v. 声称；索要', example: 'He claimed to be innocent.', category: '高频' },
    { word: 'clarify', phonetic: '/ˈklærəfaɪ/', meaning: 'v. 澄清', example: 'Could you clarify your point?', category: '中频' },
    { word: 'classify', phonetic: '/ˈklæsɪfaɪ/', meaning: 'v. 分类', example: 'Books are classified by subject.', category: '中频' },
    { word: 'climate', phonetic: '/ˈklaɪmət/', meaning: 'n. 气候', example: 'Climate change is a global issue.', category: '高频' },
    { word: 'collapse', phonetic: '/kəˈlæps/', meaning: 'v./n. 倒塌；崩溃', example: 'The building collapsed.', category: '中频' },
    { word: 'combine', phonetic: '/kəmˈbaɪn/', meaning: 'v. 结合', example: 'Combine theory with practice.', category: '高频' },
    { word: 'comment', phonetic: '/ˈkɑːment/', meaning: 'n./v. 评论', example: 'He refused to comment.', category: '高频' },
    { word: 'commit', phonetic: '/kəˈmɪt/', meaning: 'v. 犯(罪)；承诺', example: 'He committed himself to the cause.', category: '中频' },
    { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: 'v. 交流，沟通', example: 'We communicate via email.', category: '高频' },
    { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: 'n. 社区；团体', example: 'The community came together.', category: '高频' },
    { word: 'compare', phonetic: '/kəmˈper/', meaning: 'v. 比较', example: 'Compare the two options.', category: '高频' },
    { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争', example: 'Companies compete for market share.', category: '高频' },
    { word: 'complain', phonetic: '/kəmˈpleɪn/', meaning: 'v. 抱怨', example: 'Customers complained about the service.', category: '中频' },
    { word: 'complete', phonetic: '/kəmˈpliːt/', meaning: 'adj. 完整的; v. 完成', example: 'The project is complete.', category: '高频' },
    { word: 'complex', phonetic: '/kəmˈpleks/', meaning: 'adj. 复杂的', example: 'The problem is complex.', category: '高频' },
    { word: 'component', phonetic: '/kəmˈpoʊnənt/', meaning: 'n. 组成部分', example: 'Trust is a key component of friendship.', category: '中频' },
    { word: 'compose', phonetic: '/kəmˈpoʊz/', meaning: 'v. 组成；创作', example: 'Water is composed of hydrogen and oxygen.', category: '中频' },
    { word: 'comprehend', phonetic: '/ˌkɑːmprɪˈhend/', meaning: 'v. 理解', example: 'I cannot comprehend his actions.', category: '中频' },
    { word: 'concentrate', phonetic: '/ˈkɑːnsəntreɪt/', meaning: 'v. 集中', example: 'Concentrate on your studies.', category: '高频' },
    { word: 'concept', phonetic: '/ˈkɑːnsept/', meaning: 'n. 概念', example: 'The concept of freedom is important.', category: '高频' },
    { word: 'concern', phonetic: '/kənˈsɜːrn/', meaning: 'n. 关心; v. 涉及', example: 'This concerns all of us.', category: '高频' },
    { word: 'conclude', phonetic: '/kənˈkluːd/', meaning: 'v. 总结；断定', example: 'What do you conclude from the data?', category: '高频' },
    { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: 'n. 条件；状况', example: 'Living conditions have improved.', category: '高频' },
    { word: 'conduct', phonetic: '/kənˈdʌkt/', meaning: 'v. 实施; n. 行为', example: 'The experiment was conducted carefully.', category: '高频' },
    { word: 'conference', phonetic: '/ˈkɑːnfərəns/', meaning: 'n. 会议', example: 'She attended a conference.', category: '中频' },
    { word: 'confident', phonetic: '/ˈkɑːnfɪdənt/', meaning: 'adj. 自信的', example: 'She is confident of success.', category: '中频' },
    { word: 'confirm', phonetic: '/kənˈfɜːrm/', meaning: 'v. 确认', example: 'Please confirm your reservation.', category: '中频' },
    { word: 'conflict', phonetic: '/ˈkɑːnflɪkt/', meaning: 'n. 冲突', example: 'The two accounts conflict.', category: '中频' },
    { word: 'connect', phonetic: '/kəˈnekt/', meaning: 'v. 连接', example: 'The bridge connects the two cities.', category: '高频' },
    { word: 'conscious', phonetic: '/ˈkɑːnʃəs/', meaning: 'adj. 有意识的', example: 'He was conscious of the danger.', category: '中频' },
    { word: 'consequence', phonetic: '/ˈkɑːnsɪkwens/', meaning: 'n. 后果', example: 'Actions have consequences.', category: '高频' },
    { word: 'conservation', phonetic: '/ˌkɑːnsərˈveɪʃn/', meaning: 'n. 保护', example: 'Wildlife conservation is important.', category: '中频' },
    { word: 'consider', phonetic: '/kənˈsɪdər/', meaning: 'v. 考虑', example: 'Consider all the options.', category: '高频' },
    { word: 'consistent', phonetic: '/kənˈsɪstənt/', meaning: 'adj. 一致的', example: 'His story is consistent with the facts.', category: '中频' },
    { word: 'constant', phonetic: '/ˈkɑːnstənt/', meaning: 'adj. 持续的; n. 常数', example: 'The constant noise is annoying.', category: '中频' },
    { word: 'construct', phonetic: '/kənˈstrʌkt/', meaning: 'v. 建造', example: 'They constructed a new bridge.', category: '中频' },
    { word: 'consume', phonetic: '/kənˈsuːm/', meaning: 'v. 消费；消耗', example: 'We consume too much energy.', category: '高频' },
    { word: 'contact', phonetic: '/ˈkɑːntækt/', meaning: 'n./v. 联系', example: 'Stay in contact with your team.', category: '高频' },
    { word: 'contain', phonetic: '/kənˈteɪn/', meaning: 'v. 包含', example: 'The box contains books.', category: '高频' },
    { word: 'contemporary', phonetic: '/kənˈtempəreri/', meaning: 'adj. 当代的', example: 'Contemporary art is diverse.', category: '中频' },
    { word: 'content', phonetic: '/ˈkɑːntent/', meaning: 'n. 内容', example: 'The content of the article is interesting.', category: '高频' },
    { word: 'contest', phonetic: '/ˈkɑːntest/', meaning: 'n. 比赛; v. 争夺', example: 'She won the speech contest.', category: '中频' },
    { word: 'context', phonetic: '/ˈkɑːntekst/', meaning: 'n. 上下文；背景', example: 'Interpret the word in context.', category: '高频' },
    { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: 'v. 继续', example: 'The rain continued all day.', category: '高频' },
    { word: 'contract', phonetic: '/ˈkɑːntrækt/', meaning: 'n. 合同', example: 'Sign the contract.', category: '中频' },
    { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: 'v. 贡献；导致', example: 'Stress contributes to illness.', category: '高频' },
    { word: 'control', phonetic: '/kənˈtroʊl/', meaning: 'n./v. 控制', example: 'Keep the situation under control.', category: '高频' },
    { word: 'controversy', phonetic: '/ˈkɑːntrəvɜːrsi/', meaning: 'n. 争议', example: 'The decision caused controversy.', category: '中频' },
    { word: 'convenient', phonetic: '/kənˈviːniənt/', meaning: 'adj. 方便的', example: 'This location is convenient.', category: '中频' },
    { word: 'convince', phonetic: '/kənˈvɪns/', meaning: 'v. 说服', example: 'I convinced him to join us.', category: '中频' },
    { word: 'cooperate', phonetic: '/koʊˈɑːpəreɪt/', meaning: 'v. 合作', example: 'The teams cooperated on the project.', category: '中频' },
    { word: 'correspond', phonetic: '/ˌkɔːrəˈspɑːnd/', meaning: 'v. 对应；通信', example: 'The numbers correspond to codes.', category: '中频' },
    { word: 'create', phonetic: '/kriˈeɪt/', meaning: 'v. 创造', example: 'Artists create beautiful works.', category: '高频' },
    { word: 'creative', phonetic: '/kriˈeɪtɪv/', meaning: 'adj. 创造性的', example: 'Creative thinking is valuable.', category: '高频' },
    { word: 'critical', phonetic: '/ˈkrɪtɪkl/', meaning: 'adj. 批评的；关键的', example: 'Critical thinking is essential.', category: '高频' },
    { word: 'culture', phonetic: '/ˈkʌltʃər/', meaning: 'n. 文化', example: 'Chinese culture is rich and diverse.', category: '高频' },
    { word: 'curious', phonetic: '/ˈkjʊriəs/', meaning: 'adj. 好奇的', example: 'Children are naturally curious.', category: '中频' },
    { word: 'current', phonetic: '/ˈkɜːrənt/', meaning: 'adj. 当前的; n. 水流', example: 'Current events affect us all.', category: '高频' },
    { word: 'debate', phonetic: '/dɪˈbeɪt/', meaning: 'n./v. 辩论', example: 'The issue sparked debate.', category: '中频' },
    { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: 'n. 十年', example: 'Over the past decade, technology advanced.', category: '高频' },
    { word: 'declare', phonetic: '/dɪˈkler/', meaning: 'v. 宣布', example: 'They declared their independence.', category: '中频' },
    { word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: 'v./n. 下降；衰退', example: 'The economy declined.', category: '高频' },
    { word: 'decrease', phonetic: '/dɪˈkriːs/', meaning: 'v./n. 减少', example: 'The population decreased.', category: '高频' },
    { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: 'v./n. 击败', example: 'They defeated the enemy.', category: '中频' },
    { word: 'defend', phonetic: '/dɪˈfend/', meaning: 'v. 防御；辩护', example: 'We must defend our rights.', category: '中频' },
    { word: 'define', phonetic: '/dɪˈfaɪn/', meaning: 'v. 定义', example: 'How do you define success?', category: '高频' },
    { word: 'definitely', phonetic: '/ˈdefɪnətli/', meaning: 'adv. 肯定地', example: 'It is definitely worth trying.', category: '中频' },
    { word: 'deliver', phonetic: '/dɪˈlɪvər/', meaning: 'v. 递送；发表', example: 'She delivered a speech.', category: '高频' },
    { word: 'demand', phonetic: '/dɪˈmænd/', meaning: 'n./v. 需求；要求', example: 'The product is in high demand.', category: '高频' },
    { word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', meaning: 'v. 示范；证明', example: 'The experiment demonstrates the principle.', category: '高频' },
    { word: 'deny', phonetic: '/dɪˈnaɪ/', meaning: 'v. 否认；拒绝', example: 'He denied the allegations.', category: '中频' },
    { word: 'depend', phonetic: '/dɪˈpend/', meaning: 'v. 依赖', example: 'It depends on the weather.', category: '高频' },
    { word: 'depress', phonetic: '/dɪˈpres/', meaning: 'v. 使沮丧', example: 'The news depressed him.', category: '中频' },
    { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: 'v. 源自', example: 'The word derives from Latin.', category: '中频' },
    { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning: 'v. 描述', example: 'Describe what you saw.', category: '高频' },
    { word: 'deserve', phonetic: '/dɪˈzɜːrv/', meaning: 'v. 值得', example: 'You deserve a reward.', category: '中频' },
    { word: 'design', phonetic: '/dɪˈzaɪn/', meaning: 'v./n. 设计', example: 'She designed the building.', category: '高频' },
    { word: 'desire', phonetic: '/dɪˈzaɪər/', meaning: 'n./v. 渴望', example: 'He had a strong desire to learn.', category: '高频' },
    { word: 'desperate', phonetic: '/ˈdespərət/', meaning: 'adj. 绝望的', example: 'They were desperate for help.', category: '中频' },
    { word: 'despite', phonetic: '/dɪˈspaɪt/', meaning: 'prep. 尽管', example: 'Despite the rain, we went out.', category: '高频' },
    { word: 'destroy', phonetic: '/dɪˈstrɔɪ/', meaning: 'v. 破坏', example: 'The fire destroyed the building.', category: '中频' },
    { word: 'determine', phonetic: '/dɪˈtɜːrmɪn/', meaning: 'v. 决定；确定', example: 'We need to determine the cause.', category: '高频' },
    { word: 'develop', phonetic: '/dɪˈveləp/', meaning: 'v. 发展；开发', example: 'The country developed rapidly.', category: '高频' },
    { word: 'device', phonetic: '/dɪˈvaɪs/', meaning: 'n. 设备', example: 'Electronic devices are everywhere.', category: '中频' },
    { word: 'devote', phonetic: '/dɪˈvoʊt/', meaning: 'v. 致力于', example: 'She devoted her life to education.', category: '中频' },
    { word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/', meaning: 'v. 区分', example: 'Can you distinguish the two?', category: '中频' },
    { word: 'distribute', phonetic: '/dɪˈstrɪbjuːt/', meaning: 'v. 分配；分发', example: 'Distribute the materials to students.', category: '中频' },
    { word: 'domestic', phonetic: '/dəˈmestɪk/', meaning: 'adj. 国内的；家庭的', example: 'Domestic sales increased.', category: '中频' },
    { word: 'dominate', phonetic: '/ˈdɑːmɪneɪt/', meaning: 'v. 支配，主导', example: 'The company dominates the market.', category: '中频' },
    { word: 'dramatic', phonetic: '/drəˈmætɪk/', meaning: 'adj. 戏剧性的', example: 'There was a dramatic change.', category: '中频' },
    { word: 'economy', phonetic: '/ɪˈkɑːnəmi/', meaning: 'n. 经济', example: 'The economy is growing.', category: '高频' },
    { word: 'educate', phonetic: '/ˈedʒukeɪt/', meaning: 'v. 教育', example: 'Education is the key to success.', category: '高频' },
    { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: 'adj. 高效的', example: 'The new system is efficient.', category: '中频' },
    { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning: 'v. 消除', example: 'We need to eliminate waste.', category: '中频' },
    { word: 'emerge', phonetic: '/iˈmɜːrdʒ/', meaning: 'v. 出现', example: 'New technologies emerge daily.', category: '中频' },
    { word: 'emotion', phonetic: '/ɪˈmoʊʃn/', meaning: 'n. 情感', example: 'She expressed her emotions freely.', category: '中频' },
    { word: 'emphasis', phonetic: '/ˈemfəsɪs/', meaning: 'n. 强调', example: 'The emphasis is on quality.', category: '中频' },
    { word: 'employ', phonetic: '/ɪmˈplɔɪ/', meaning: 'v. 雇用; 使用', example: 'The company employs 500 people.', category: '高频' },
    { word: 'enable', phonetic: '/ɪˈneɪbl/', meaning: 'v. 使能够', example: 'Technology enables us to connect.', category: '高频' },
    { word: 'encounter', phonetic: '/ɪnˈkaʊntər/', meaning: 'v. 遭遇', example: 'We encountered many difficulties.', category: '中频' },
    { word: 'encourage', phonetic: '/ɪnˈkɜːrɪdʒ/', meaning: 'v. 鼓励', example: 'Teachers encourage students to ask questions.', category: '高频' },
    { word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', meaning: 'v. 参与；吸引', example: 'The book engaged my attention.', category: '中频' },
    { word: 'enhance', phonetic: '/ɪnˈhæns/', meaning: 'v. 增强', example: 'Exercise enhances your health.', category: '中频' },
    { word: 'enormous', phonetic: '/ɪˈnɔːrməs/', meaning: 'adj. 巨大的', example: 'The project requires enormous effort.', category: '中频' },
    { word: 'ensure', phonetic: '/ɪnˈʃʊr/', meaning: 'v. 确保', example: 'Ensure the door is locked.', category: '高频' },
    { word: 'enterprise', phonetic: '/ˈentərpraɪz/', meaning: 'n. 企业', example: 'Small enterprises drive innovation.', category: '中频' },
    { word: 'entertain', phonetic: '/ˌentərˈteɪn/', meaning: 'v. 娱乐', example: 'The show entertained the audience.', category: '中频' },
    { word: 'enthusiasm', phonetic: '/ɪnˈθuːziæzəm/', meaning: 'n. 热情', example: 'She showed great enthusiasm.', category: '中频' },
    { word: 'entire', phonetic: '/ɪnˈtaɪər/', meaning: 'adj. 全部的', example: 'The entire class passed.', category: '高频' },
    { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: 'n. 环境', example: 'Protect the environment.', category: '高频' },
    { word: 'equal', phonetic: '/ˈiːkwəl/', meaning: 'adj. 相等的; v. 等于', example: 'All people are equal.', category: '高频' },
    { word: 'equipment', phonetic: '/ɪˈkwɪpmənt/', meaning: 'n. 设备', example: 'The laboratory has modern equipment.', category: '中频' },
    { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: 'v. 建立', example: 'They established a new company.', category: '高频' },
    { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: 'v./n. 估计', example: 'The cost is estimated at $1 million.', category: '中频' },
    { word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: 'v. 评价', example: 'Evaluate the results carefully.', category: '中频' },
    { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: 'n. 证据', example: 'The evidence supports the theory.', category: '高频' },
    { word: 'evolve', phonetic: '/ɪˈvɑːlv/', meaning: 'v. 进化；发展', example: 'Species evolve over time.', category: '中频' },
    { word: 'examine', phonetic: '/ɪɡˈzæmɪn/', meaning: 'v. 检查', example: 'Examine the evidence carefully.', category: '高频' },
    { word: 'example', phonetic: '/ɪɡˈzæmpl/', meaning: 'n. 例子', example: 'Give me an example.', category: '高频' },
    { word: 'exceed', phonetic: '/ɪkˈsiːd/', meaning: 'v. 超过', example: 'The cost exceeded our budget.', category: '中频' },
    { word: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', meaning: 'v./n. 交换', example: 'We exchanged ideas.', category: '中频' },
    { word: 'exclude', phonetic: '/ɪkˈskluːd/', meaning: 'v. 排除', example: 'Some items are excluded.', category: '中频' },
    { word: 'execute', phonetic: '/ˈeksɪkjuːt/', meaning: 'v. 执行', example: 'Execute the plan carefully.', category: '中频' },
    { word: 'exercise', phonetic: '/ˈeksərsaɪz/', meaning: 'n./v. 锻炼', example: 'Regular exercise is important.', category: '高频' },
    { word: 'exhibit', phonetic: '/ɪɡˈzɪbɪt/', meaning: 'v. 展示', example: 'The museum exhibits ancient artifacts.', category: '中频' },
    { word: 'exist', phonetic: '/ɪɡˈzɪst/', meaning: 'v. 存在', example: 'Do ghosts really exist?', category: '高频' },
    { word: 'expand', phonetic: '/ɪkˈspænd/', meaning: 'v. 扩展', example: 'The company expanded overseas.', category: '高频' },
    { word: 'expect', phonetic: '/ɪkˈspekt/', meaning: 'v. 期待', example: 'I expect good results.', category: '高频' },
    { word: 'expense', phonetic: '/ɪkˈspens/', meaning: 'n. 费用', example: 'Living expenses are high.', category: '中频' },
    { word: 'experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: 'n. 实验', example: 'Conduct an experiment.', category: '中频' },
    { word: 'explain', phonetic: '/ɪkˈspleɪn/', meaning: 'v. 解释', example: 'Can you explain this?', category: '高频' },
    { word: 'explore', phonetic: '/ɪkˈsplɔːr/', meaning: 'v. 探索', example: 'Explore new possibilities.', category: '高频' },
    { word: 'export', phonetic: '/ˈekspɔːrt/', meaning: 'n./v. 出口', example: 'The country exports oil.', category: '中频' },
    { word: 'expose', phonetic: '/ɪkˈspoʊz/', meaning: 'v. 暴露', example: 'Don\'t expose it to sunlight.', category: '中频' },
    { word: 'express', phonetic: '/ɪkˈspres/', meaning: 'v. 表达', example: 'Express your opinion freely.', category: '高频' },
    { word: 'extend', phonetic: '/ɪkˈstend/', meaning: 'v. 延伸；扩展', example: 'The road extends for miles.', category: '高频' },
    { word: 'external', phonetic: '/ɪkˈstɜːrnl/', meaning: 'adj. 外部的', example: 'External factors influence decisions.', category: '中频' },
    { word: 'extreme', phonetic: '/ɪkˈstriːm/', meaning: 'adj. 极端的', example: 'Extreme weather is becoming common.', category: '中频' },
    { word: 'facility', phonetic: '/fəˈsɪləti/', meaning: 'n. 设施', example: 'The sports facilities are excellent.', category: '中频' },
    { word: 'factor', phonetic: '/ˈfæktər/', meaning: 'n. 因素', example: 'Many factors contribute to success.', category: '高频' },
    { word: 'familiar', phonetic: '/fəˈmɪliər/', meaning: 'adj. 熟悉的', example: 'I am familiar with the topic.', category: '高频' },
    { word: 'feature', phonetic: '/ˈfiːtʃər/', meaning: 'n. 特征', example: 'The product has unique features.', category: '高频' },
    { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning: 'n. 金融; v. 资助', example: 'The project needs finance.', category: '中频' },
    { word: 'flexible', phonetic: '/ˈfleksəbl/', meaning: 'adj. 灵活的', example: 'We need a flexible approach.', category: '中频' },
    { word: 'forecast', phonetic: '/ˈfɔːrkæst/', meaning: 'v./n. 预测', example: 'The weather forecast predicts rain.', category: '中频' },
    { word: 'foundation', phonetic: '/faʊnˈdeɪʃn/', meaning: 'n. 基础；基金会', example: 'Education is the foundation of society.', category: '高频' },
    { word: 'frequent', phonetic: '/ˈfriːkwənt/', meaning: 'adj. 频繁的', example: 'Frequent exercise is beneficial.', category: '中频' },
    { word: 'function', phonetic: '/ˈfʌŋkʃn/', meaning: 'n. 功能; v. 运行', example: 'What is the function of this device?', category: '高频' },
    { word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: 'adj. 基本的', example: 'Fundamental rights must be protected.', category: '中频' },
    { word: 'generate', phonetic: '/ˈdʒenəreɪt/', meaning: 'v. 产生', example: 'Solar panels generate electricity.', category: '高频' },
    { word: 'generous', phonetic: '/ˈdʒenərəs/', meaning: 'adj. 慷慨的', example: 'She is generous with her time.', category: '中频' },
    { word: 'global', phonetic: '/ˈɡloʊbl/', meaning: 'adj. 全球的', example: 'Global trade is increasing.', category: '高频' },
    { word: 'gradual', phonetic: '/ˈɡrædʒuəl/', meaning: 'adj. 逐渐的', example: 'There was a gradual improvement.', category: '中频' },
    { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: 'v./n. 保证', example: 'We guarantee your satisfaction.', category: '中频' },
    { word: 'harmony', phonetic: '/ˈhɑːrməni/', meaning: 'n. 和谐', example: 'Live in harmony with nature.', category: '中频' },
    { word: 'hesitate', phonetic: '/ˈhezɪteɪt/', meaning: 'v. 犹豫', example: 'Don\'t hesitate to ask.', category: '中频' },
    { word: 'highlight', phonetic: '/ˈhaɪlaɪt/', meaning: 'v. 强调', example: 'The report highlights key issues.', category: '中频' },
    { word: 'identify', phonetic: '/aɪˈdentɪfaɪ/', meaning: 'v. 识别；确认', example: 'Identify the problem first.', category: '高频' },
    { word: 'ignore', phonetic: '/ɪɡˈnɔːr/', meaning: 'v. 忽视', example: 'Don\'t ignore the warning signs.', category: '高频' },
    { word: 'illustrate', phonetic: '/ˈɪləstreɪt/', meaning: 'v. 说明；举例', example: 'The diagram illustrates the process.', category: '中频' },
    { word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: 'v. 想象', example: 'Imagine a world without war.', category: '高频' },
    { word: 'immediate', phonetic: '/ɪˈmiːdiət/', meaning: 'adj. 立即的', example: 'Take immediate action.', category: '高频' },
    { word: 'impact', phonetic: '/ˈɪmpækt/', meaning: 'n./v. 影响', example: 'The internet has a huge impact.', category: '高频' },
    { word: 'implement', phonetic: '/ˈɪmplɪment/', meaning: 'v. 实施', example: 'Implement the new policy.', category: '中频' },
    { word: 'imply', phonetic: '/ɪmˈplaɪ/', meaning: 'v. 暗示', example: 'What do you imply?', category: '中频' },
    { word: 'impose', phonetic: '/ɪmˈpoʊz/', meaning: 'v. 强加', example: 'Don\'t impose your views on others.', category: '中频' },
    { word: 'impress', phonetic: '/ɪmˈpres/', meaning: 'v. 给...深刻印象', example: 'She impressed everyone with her speech.', category: '中频' },
    { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: 'v. 改善', example: 'We need to improve efficiency.', category: '高频' },
    { word: 'include', phonetic: '/ɪnˈkluːd/', meaning: 'v. 包括', example: 'The price includes tax.', category: '高频' },
    { word: 'increase', phonetic: '/ɪnˈkriːs/', meaning: 'v./n. 增加', example: 'Sales increased by 20%.', category: '高频' },
    { word: 'indicate', phonetic: '/ˈɪndɪkeɪt/', meaning: 'v. 表明', example: 'The data indicates a trend.', category: '高频' },
    { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning: 'adj. 个人的; n. 个人', example: 'Respect individual rights.', category: '高频' },
    { word: 'industry', phonetic: '/ˈɪndəstri/', meaning: 'n. 工业; 行业', example: 'The automotive industry is growing.', category: '高频' },
    { word: 'influence', phonetic: '/ˈɪnfluəns/', meaning: 'n./v. 影响', example: 'Parents influence their children.', category: '高频' },
    { word: 'inform', phonetic: '/ɪnˈfɔːrm/', meaning: 'v. 通知', example: 'Please inform me of any changes.', category: '中频' },
    { word: 'initiative', phonetic: '/ɪˈnɪʃətɪv/', meaning: 'n. 主动；倡议', example: 'She took the initiative to help.', category: '中频' },
    { word: 'innovate', phonetic: '/ˈɪnəveɪt/', meaning: 'v. 创新', example: 'Companies must innovate to survive.', category: '中频' },
    { word: 'inspect', phonetic: '/ɪnˈspekt/', meaning: 'v. 检查', example: 'Inspect the product for defects.', category: '中频' },
    { word: 'inspire', phonetic: '/ɪnˈspaɪər/', meaning: 'v. 激励', example: 'Great leaders inspire others.', category: '中频' },
    { word: 'institute', phonetic: '/ˈɪnstɪtuːt/', meaning: 'n. 研究所; v. 建立', example: 'She works at a research institute.', category: '中频' },
    { word: 'instruct', phonetic: '/ɪnˈstrʌkt/', meaning: 'v. 指导', example: 'The manual instructs users on assembly.', category: '中频' },
    { word: 'insure', phonetic: '/ɪnˈʃʊr/', meaning: 'v. 投保', example: 'You should insure your car.', category: '中频' },
    { word: 'integrate', phonetic: '/ˈɪntɪɡreɪt/', meaning: 'v. 整合', example: 'Integrate theory with practice.', category: '中频' },
    { word: 'intellectual', phonetic: '/ˌɪntəˈlektʃuəl/', meaning: 'adj. 智力的; n. 知识分子', example: 'Intellectual property must be protected.', category: '中频' },
    { word: 'intelligence', phonetic: '/ɪnˈtelɪdʒəns/', meaning: 'n. 智力；情报', example: 'Artificial intelligence is advancing.', category: '高频' },
    { word: 'intend', phonetic: '/ɪnˈtend/', meaning: 'v. 打算', example: 'I intend to finish this today.', category: '高频' },
    { word: 'interact', phonetic: '/ˌɪntərˈækt/', meaning: 'v. 互动', example: 'Students interact with each other.', category: '中频' },
    { word: 'interest', phonetic: '/ˈɪntrəst/', meaning: 'n. 兴趣；利益', example: 'I have an interest in art.', category: '高频' },
    { word: 'interpret', phonetic: '/ɪnˈtɜːrprɪt/', meaning: 'v. 解释；口译', example: 'How do you interpret this data?', category: '中频' },
    { word: 'interrupt', phonetic: '/ˌɪntəˈrʌpt/', meaning: 'v. 打断', example: 'Don\'t interrupt me.', category: '中频' },
    { word: 'invest', phonetic: '/ɪnˈvest/', meaning: 'v. 投资', example: 'Invest in your education.', category: '高频' },
    { word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', meaning: 'v. 调查', example: 'The police are investigating.', category: '中频' },
    { word: 'involve', phonetic: '/ɪnˈvɑːlv/', meaning: 'v. 涉及；参与', example: 'The project involves teamwork.', category: '高频' },
    { word: 'isolate', phonetic: '/ˈaɪsəleɪt/', meaning: 'v. 隔离', example: 'The patient was isolated.', category: '中频' },
    { word: 'issue', phonetic: '/ˈɪʃuː/', meaning: 'n. 问题; v. 发布', example: 'Environmental issues are important.', category: '高频' },
    { word: 'justify', phonetic: '/ˈdʒʌstɪfaɪ/', meaning: 'v. 证明...正当', example: 'Can you justify your decision?', category: '中频' },
    { word: 'knowledge', phonetic: '/ˈnɑːlɪdʒ/', meaning: 'n. 知识', example: 'Knowledge is power.', category: '高频' },
    { word: 'labor', phonetic: '/ˈleɪbər/', meaning: 'n. 劳动', example: 'Manual labor is hard work.', category: '高频' },
    { word: 'launch', phonetic: '/lɔːntʃ/', meaning: 'v. 发射；启动', example: 'They launched a new product.', category: '中频' },
    { word: 'legal', phonetic: '/ˈliːɡl/', meaning: 'adj. 法律的；合法的', example: 'Seek legal advice.', category: '高频' },
    { word: 'liberal', phonetic: '/ˈlɪbərəl/', meaning: 'adj. 自由的；开放的', example: 'Liberal arts education broadens minds.', category: '中频' },
    { word: 'likely', phonetic: '/ˈlaɪkli/', meaning: 'adj./adv. 可能的', example: 'It is likely to rain.', category: '高频' },
    { word: 'limit', phonetic: '/ˈlɪmɪt/', meaning: 'n./v. 限制', example: 'There is a limit to what we can do.', category: '高频' },
    { word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: 'v. 维持；保养', example: 'Maintain good health through exercise.', category: '高频' },
    { word: 'major', phonetic: '/ˈmeɪdʒər/', meaning: 'adj. 主要的; n. 专业', example: 'The major issue is funding.', category: '高频' },
    { word: 'manage', phonetic: '/ˈmænɪdʒ/', meaning: 'v. 管理；设法', example: 'She manages the team well.', category: '高频' },
    { word: 'manufacture', phonetic: '/ˌmænjuˈfæktʃər/', meaning: 'v. 制造', example: 'The factory manufactures cars.', category: '中频' },
    { word: 'measure', phonetic: '/ˈmeʒər/', meaning: 'v. 测量; n. 措施', example: 'We need to take measures.', category: '高频' },
    { word: 'media', phonetic: '/ˈmiːdiə/', meaning: 'n. 媒体', example: 'Social media connects people.', category: '高频' },
    { word: 'mental', phonetic: '/ˈmentl/', meaning: 'adj. 精神的', example: 'Mental health is important.', category: '中频' },
    { word: 'method', phonetic: '/ˈmeθəd/', meaning: 'n. 方法', example: 'Try a different method.', category: '高频' },
    { word: 'minimum', phonetic: '/ˈmɪnɪməm/', meaning: 'adj./n. 最小量', example: 'Pay the minimum amount.', category: '中频' },
    { word: 'modify', phonetic: '/ˈmɑːdɪfaɪ/', meaning: 'v. 修改', example: 'We need to modify the plan.', category: '中频' },
    { word: 'monitor', phonetic: '/ˈmɑːnɪtər/', meaning: 'v. 监控', example: 'Monitor the situation closely.', category: '中频' },
    { word: 'motivate', phonetic: '/ˈmoʊtɪveɪt/', meaning: 'v. 激励', example: 'Good leaders motivate their teams.', category: '中频' },
    { word: 'negotiate', phonetic: '/nɪˈɡoʊʃieɪt/', meaning: 'v. 谈判', example: 'They negotiated a peace deal.', category: '中频' },
    { word: 'network', phonetic: '/ˈnetwɜːrk/', meaning: 'n. 网络', example: 'Build a professional network.', category: '高频' },
    { word: 'nevertheless', phonetic: '/ˌnevərðəˈles/', meaning: 'adv. 然而', example: 'It was difficult; nevertheless, we succeeded.', category: '中频' },
    { word: 'normal', phonetic: '/ˈnɔːrml/', meaning: 'adj. 正常的', example: 'Return to normal life.', category: '高频' },
    { word: 'numerous', phonetic: '/ˈnuːmərəs/', meaning: 'adj. 众多的', example: 'Numerous studies confirm this.', category: '中频' },
    { word: 'obtain', phonetic: '/əbˈteɪn/', meaning: 'v. 获得', example: 'Obtain permission first.', category: '高频' },
    { word: 'obvious', phonetic: '/ˈɑːbviəs/', meaning: 'adj. 明显的', example: 'It is obvious that he is lying.', category: '高频' },
    { word: 'occupy', phonetic: '/ˈɑːkjupaɪ/', meaning: 'v. 占据', example: 'The city was occupied.', category: '中频' },
    { word: 'operate', phonetic: '/ˈɑːpəreɪt/', meaning: 'v. 操作；经营', example: 'The machine operates smoothly.', category: '高频' },
    { word: 'opinion', phonetic: '/əˈpɪnjən/', meaning: 'n. 意见', example: 'In my opinion, it is a good idea.', category: '高频' },
    { word: 'opponent', phonetic: '/əˈpoʊnənt/', meaning: 'n. 对手', example: 'He defeated his opponent.', category: '中频' },
    { word: 'opportunity', phonetic: '/ˌɑːpərˈtuːnəti/', meaning: 'n. 机会', example: 'Don\'t miss this opportunity.', category: '高频' },
    { word: 'oppose', phonetic: '/əˈpoʊz/', meaning: 'v. 反对', example: 'Many people oppose the proposal.', category: '中频' },
    { word: 'organize', phonetic: '/ˈɔːrɡənaɪz/', meaning: 'v. 组织', example: 'Organize your thoughts.', category: '高频' },
    { word: 'original', phonetic: '/əˈrɪdʒənl/', meaning: 'adj. 原始的；原创的', example: 'The original plan was better.', category: '高频' },
    { word: 'overcome', phonetic: '/ˌoʊvərˈkʌm/', meaning: 'v. 克服', example: 'Overcome obstacles with determination.', category: '中频' },
    { word: 'participate', phonetic: '/pɑːrˈtɪsɪpeɪt/', meaning: 'v. 参与', example: 'Everyone should participate.', category: '中频' },
    { word: 'particular', phonetic: '/pərˈtɪkjələr/', meaning: 'adj. 特定的; 特别的', example: 'Pay particular attention to details.', category: '高频' },
    { word: 'perform', phonetic: '/pərˈfɔːrm/', meaning: 'v. 表演；执行', example: 'The team performed well.', category: '高频' },
    { word: 'period', phonetic: '/ˈpɪriəd/', meaning: 'n. 时期', example: 'This period of history is fascinating.', category: '高频' },
    { word: 'permit', phonetic: '/pərˈmɪt/', meaning: 'v. 允许', example: 'Smoking is not permitted.', category: '中频' },
    { word: 'persist', phonetic: '/pərˈsɪst/', meaning: 'v. 坚持', example: 'Persist in your efforts.', category: '中频' },
    { word: 'personality', phonetic: '/ˌpɜːrsəˈnæləti/', meaning: 'n. 个性', example: 'She has a strong personality.', category: '中频' },
    { word: 'perspective', phonetic: '/pərˈspektɪv/', meaning: 'n. 视角', example: 'Look at it from a different perspective.', category: '中频' },
    { word: 'phenomenon', phonetic: '/fəˈnɑːmɪnən/', meaning: 'n. 现象', example: 'This is a natural phenomenon.', category: '中频' },
    { word: 'philosophy', phonetic: '/fəˈlɑːsəfi/', meaning: 'n. 哲学', example: 'Eastern philosophy emphasizes harmony.', category: '中频' },
    { word: 'physical', phonetic: '/ˈfɪzɪkl/', meaning: 'adj. 身体的；物理的', example: 'Physical exercise is essential.', category: '高频' },
    { word: 'policy', phonetic: '/ˈpɑːləsi/', meaning: 'n. 政策', example: 'Government policies affect the economy.', category: '高频' },
    { word: 'political', phonetic: '/pəˈlɪtɪkl/', meaning: 'adj. 政治的', example: 'Political stability is important.', category: '高频' },
    { word: 'popular', phonetic: '/ˈpɑːpjələr/', meaning: 'adj. 流行的', example: 'The song is very popular.', category: '高频' },
    { word: 'portion', phonetic: '/ˈpɔːrʃn/', meaning: 'n. 部分', example: 'A portion of the budget is for research.', category: '中频' },
    { word: 'possess', phonetic: '/pəˈzes/', meaning: 'v. 拥有', example: 'She possesses great talent.', category: '中频' },
    { word: 'potential', phonetic: '/pəˈtenʃl/', meaning: 'adj./n. 潜力', example: 'He has great potential.', category: '高频' },
    { word: 'poverty', phonetic: '/ˈpɑːvərti/', meaning: 'n. 贫穷', example: 'Poverty remains a global challenge.', category: '中频' },
    { word: 'practice', phonetic: '/ˈpræktɪs/', meaning: 'n./v. 实践；练习', example: 'Practice makes perfect.', category: '高频' },
    { word: 'precise', phonetic: '/prɪˈsaɪs/', meaning: 'adj. 精确的', example: 'Give precise instructions.', category: '中频' },
    { word: 'predict', phonetic: '/prɪˈdɪkt/', meaning: 'v. 预测', example: 'Predict the outcome.', category: '中频' },
    { word: 'prefer', phonetic: '/prɪˈfɜːr/', meaning: 'v. 偏好', example: 'I prefer tea to coffee.', category: '高频' },
    { word: 'prepare', phonetic: '/prɪˈper/', meaning: 'v. 准备', example: 'Prepare for the exam.', category: '高频' },
    { word: 'preserve', phonetic: '/prɪˈzɜːrv/', meaning: 'v. 保护；保存', example: 'Preserve the environment.', category: '中频' },
    { word: 'prevent', phonetic: '/prɪˈvent/', meaning: 'v. 防止', example: 'Prevent disease through vaccination.', category: '高频' },
    { word: 'previous', phonetic: '/ˈpriːviəs/', meaning: 'adj. 先前的', example: 'In previous years, it was different.', category: '高频' },
    { word: 'principle', phonetic: '/ˈprɪnsəpl/', meaning: 'n. 原则', example: 'Stick to your principles.', category: '高频' },
    { word: 'priority', phonetic: '/praɪˈɔːrəti/', meaning: 'n. 优先', example: 'Set your priorities straight.', category: '中频' },
    { word: 'procedure', phonetic: '/prəˈsiːdʒər/', meaning: 'n. 程序', example: 'Follow the standard procedure.', category: '中频' },
    { word: 'process', phonetic: '/ˈprɑːses/', meaning: 'n. 过程; v. 处理', example: 'The manufacturing process is complex.', category: '高频' },
    { word: 'produce', phonetic: '/prəˈduːs/', meaning: 'v. 生产', example: 'The factory produces cars.', category: '高频' },
    { word: 'profession', phonetic: '/prəˈfeʃn/', meaning: 'n. 职业', example: 'Teaching is a noble profession.', category: '中频' },
    { word: 'profit', phonetic: '/ˈprɑːfɪt/', meaning: 'n. 利润', example: 'The company made a profit.', category: '高频' },
    { word: 'progress', phonetic: '/ˈprɑːɡres/', meaning: 'n. 进步', example: 'We are making good progress.', category: '高频' },
    { word: 'project', phonetic: '/ˈprɑːdʒekt/', meaning: 'n. 项目', example: 'The project is on schedule.', category: '高频' },
    { word: 'promote', phonetic: '/prəˈmoʊt/', meaning: 'v. 促进；提升', example: 'Exercise promotes good health.', category: '高频' },
    { word: 'proper', phonetic: '/ˈprɑːpər/', meaning: 'adj. 适当的', example: 'Use the proper tools.', category: '高频' },
    { word: 'property', phonetic: '/ˈprɑːpərti/', meaning: 'n. 财产；性质', example: 'Protect your property.', category: '中频' },
    { word: 'proportion', phonetic: '/prəˈpɔːrʃn/', meaning: 'n. 比例', example: 'A large proportion of students passed.', category: '中频' },
    { word: 'propose', phonetic: '/prəˈpoʊz/', meaning: 'v. 提议', example: 'I propose a new plan.', category: '中频' },
    { word: 'prospect', phonetic: '/ˈprɑːspekt/', meaning: 'n. 前景', example: 'Job prospects are improving.', category: '中频' },
    { word: 'protect', phonetic: '/prəˈtekt/', meaning: 'v. 保护', example: 'Protect the environment.', category: '高频' },
    { word: 'prove', phonetic: '/pruːv/', meaning: 'v. 证明', example: 'The theory was proven correct.', category: '高频' },
    { word: 'provide', phonetic: '/prəˈvaɪd/', meaning: 'v. 提供', example: 'The company provides services.', category: '高频' },
    { word: 'psychology', phonetic: '/saɪˈkɑːlədʒi/', meaning: 'n. 心理学', example: 'Psychology studies human behavior.', category: '中频' },
    { word: 'publish', phonetic: '/ˈpʌblɪʃ/', meaning: 'v. 出版', example: 'She published her first novel.', category: '中频' },
    { word: 'purchase', phonetic: '/ˈpɜːrtʃəs/', meaning: 'v./n. 购买', example: 'Make a purchase online.', category: '中频' },
    { word: 'pursue', phonetic: '/pərˈsuː/', meaning: 'v. 追求', example: 'Pursue your dreams.', category: '中频' },
    { word: 'qualify', phonetic: '/ˈkwɑːlɪfaɪ/', meaning: 'v. 使合格', example: 'The training qualifies you for the job.', category: '中频' },
    { word: 'quantity', phonetic: '/ˈkwɑːntəti/', meaning: 'n. 数量', example: 'A large quantity of goods arrived.', category: '中频' },
    { word: 'range', phonetic: '/reɪndʒ/', meaning: 'n. 范围; v. 延伸', example: 'The price range is wide.', category: '高频' },
    { word: 'rapid', phonetic: '/ˈræpɪd/', meaning: 'adj. 迅速的', example: 'Rapid economic growth.', category: '高频' },
    { word: 'rational', phonetic: '/ˈræʃnəl/', meaning: 'adj. 理性的', example: 'Make a rational decision.', category: '中频' },
    { word: 'react', phonetic: '/riˈækt/', meaning: 'v. 反应', example: 'How did he react to the news?', category: '中频' },
    { word: 'realize', phonetic: '/ˈriːəlaɪz/', meaning: 'v. 意识到；实现', example: 'I realized my mistake.', category: '高频' },
    { word: 'reasonable', phonetic: '/ˈriːznəbl/', meaning: 'adj. 合理的', example: 'The price is reasonable.', category: '高频' },
    { word: 'recognize', phonetic: '/ˈrekəɡnaɪz/', meaning: 'v. 认出；承认', example: 'I recognized her voice.', category: '高频' },
    { word: 'recommend', phonetic: '/ˌrekəˈmend/', meaning: 'v. 推荐', example: 'I recommend this book.', category: '中频' },
    { word: 'recover', phonetic: '/rɪˈkʌvər/', meaning: 'v. 恢复', example: 'She recovered from the illness.', category: '中频' },
    { word: 'reduce', phonetic: '/rɪˈduːs/', meaning: 'v. 减少', example: 'Reduce your carbon footprint.', category: '高频' },
    { word: 'refer', phonetic: '/rɪˈfɜːr/', meaning: 'v. 参考；提及', example: 'Refer to the manual.', category: '高频' },
    { word: 'reflect', phonetic: '/rɪˈflekt/', meaning: 'v. 反映；反射', example: 'The data reflects the truth.', category: '高频' },
    { word: 'reform', phonetic: '/rɪˈfɔːrm/', meaning: 'v./n. 改革', example: 'Educational reform is needed.', category: '中频' },
    { word: 'refuse', phonetic: '/rɪˈfjuːz/', meaning: 'v. 拒绝', example: 'He refused to answer.', category: '高频' },
    { word: 'regard', phonetic: '/rɪˈɡɑːrd/', meaning: 'v. 认为; n. 关心', example: 'I regard him as a friend.', category: '高频' },
    { word: 'region', phonetic: '/ˈriːdʒən/', meaning: 'n. 区域', example: 'The region is known for its wine.', category: '高频' },
    { word: 'register', phonetic: '/ˈredʒɪstər/', meaning: 'v. 登记；注册', example: 'Register for the course online.', category: '中频' },
    { word: 'regulate', phonetic: '/ˈreɡjuleɪt/', meaning: 'v. 调节；管理', example: 'The government regulates the industry.', category: '中频' },
    { word: 'reject', phonetic: '/rɪˈdʒekt/', meaning: 'v. 拒绝；驳回', example: 'The court rejected the appeal.', category: '中频' },
    { word: 'relate', phonetic: '/rɪˈleɪt/', meaning: 'v. 关联；叙述', example: 'The two events are related.', category: '高频' },
    { word: 'release', phonetic: '/rɪˈliːs/', meaning: 'v./n. 释放；发布', example: 'The new film was released.', category: '高频' },
    { word: 'relevant', phonetic: '/ˈreləvənt/', meaning: 'adj. 相关的', example: 'Is this relevant to the topic?', category: '高频' },
    { word: 'relief', phonetic: '/rɪˈliːf/', meaning: 'n. 缓解；宽慰', example: 'The medicine brought relief.', category: '中频' },
    { word: 'rely', phonetic: '/rɪˈlaɪ/', meaning: 'v. 依赖', example: 'We rely on renewable energy.', category: '高频' },
    { word: 'remain', phonetic: '/rɪˈmeɪn/', meaning: 'v. 保持；剩下', example: 'The problem remains unsolved.', category: '高频' },
    { word: 'remark', phonetic: '/rɪˈmɑːrk/', meaning: 'n./v. 评论', example: 'He made a clever remark.', category: '中频' },
    { word: 'remedy', phonetic: '/ˈremədi/', meaning: 'n. 补救；药物', example: 'There is no easy remedy.', category: '中频' },
    { word: 'remote', phonetic: '/rɪˈmoʊt/', meaning: 'adj. 遥远的', example: 'Remote areas lack infrastructure.', category: '中频' },
    { word: 'remove', phonetic: '/rɪˈmuːv/', meaning: 'v. 移除', example: 'Remove the obstacle.', category: '高频' },
    { word: 'replace', phonetic: '/rɪˈpleɪs/', meaning: 'v. 替代', example: 'Replace the old battery.', category: '高频' },
    { word: 'represent', phonetic: '/ˌreprɪˈzent/', meaning: 'v. 代表', example: 'The symbol represents peace.', category: '高频' },
    { word: 'republic', phonetic: '/rɪˈpʌblɪk/', meaning: 'n. 共和国', example: 'The republic was founded in 1949.', category: '中频' },
    { word: 'reputation', phonetic: '/ˌrepjuˈteɪʃn/', meaning: 'n. 声誉', example: 'She has a good reputation.', category: '中频' },
    { word: 'request', phonetic: '/rɪˈkwest/', meaning: 'n./v. 请求', example: 'Request more information.', category: '高频' },
    { word: 'require', phonetic: '/rɪˈkwaɪər/', meaning: 'v. 要求', example: 'This requires careful thought.', category: '高频' },
    { word: 'research', phonetic: '/rɪˈsɜːrtʃ/', meaning: 'n./v. 研究', example: 'Conduct scientific research.', category: '高频' },
    { word: 'reserve', phonetic: '/rɪˈzɜːrv/', meaning: 'v. 保留; 预订', example: 'Reserve a table for two.', category: '中频' },
    { word: 'resign', phonetic: '/rɪˈzaɪn/', meaning: 'v. 辞职', example: 'He resigned from his position.', category: '中频' },
    { word: 'resist', phonetic: '/rɪˈzɪst/', meaning: 'v. 抵抗', example: 'Resist the temptation.', category: '中频' },
    { word: 'resolve', phonetic: '/rɪˈzɑːlv/', meaning: 'v. 解决', example: 'Resolve the conflict peacefully.', category: '中频' },
    { word: 'resource', phonetic: '/ˈriːsɔːrs/', meaning: 'n. 资源', example: 'Natural resources are limited.', category: '高频' },
    { word: 'respond', phonetic: '/rɪˈspɑːnd/', meaning: 'v. 回应', example: 'Respond to the question.', category: '高频' },
    { word: 'responsible', phonetic: '/rɪˈspɑːnsəbl/', meaning: 'adj. 负责的', example: 'Who is responsible for this?', category: '高频' },
    { word: 'restore', phonetic: '/rɪˈstɔːr/', meaning: 'v. 恢复', example: 'Restore peace and order.', category: '中频' },
    { word: 'restrict', phonetic: '/rɪˈstrɪkt/', meaning: 'v. 限制', example: 'Access is restricted.', category: '中频' },
    { word: 'reveal', phonetic: '/rɪˈviːl/', meaning: 'v. 揭示', example: 'The investigation revealed the truth.', category: '中频' },
    { word: 'revenue', phonetic: '/ˈrevənuː/', meaning: 'n. 收入', example: 'Tax revenue increased.', category: '中频' },
    { word: 'reverse', phonetic: '/rɪˈvɜːrs/', meaning: 'v. 逆转; adj. 相反的', example: 'Reverse the decision.', category: '中频' },
    { word: 'revolution', phonetic: '/ˌrevəˈluːʃn/', meaning: 'n. 革命', example: 'The industrial revolution changed the world.', category: '中频' },
    { word: 'risk', phonetic: '/rɪsk/', meaning: 'n./v. 风险', example: 'Take a calculated risk.', category: '高频' },
    { word: 'rural', phonetic: '/ˈrʊrəl/', meaning: 'adj. 农村的', example: 'Rural areas need more investment.', category: '中频' },
    { word: 'satisfy', phonetic: '/ˈsætɪsfaɪ/', meaning: 'v. 满足', example: 'Satisfy the customer\'s needs.', category: '中频' },
    { word: 'schedule', phonetic: '/ˈskedʒuːl/', meaning: 'n. 时间表', example: 'The project is on schedule.', category: '高频' },
    { word: 'scholar', phonetic: '/ˈskɑːlər/', meaning: 'n. 学者', example: 'She is a respected scholar.', category: '中频' },
    { word: 'security', phonetic: '/sɪˈkjʊrəti/', meaning: 'n. 安全', example: 'National security is paramount.', category: '高频' },
    { word: 'senior', phonetic: '/ˈsiːniər/', meaning: 'adj. 高级的；年长的', example: 'Senior citizens deserve respect.', category: '中频' },
    { word: 'sensitive', phonetic: '/ˈsensətɪv/', meaning: 'adj. 敏感的', example: 'Be sensitive to others\' feelings.', category: '中频' },
    { word: 'separate', phonetic: '/ˈsepəreɪt/', meaning: 'v. 分开; adj. 分开的', example: 'Separate the items by category.', category: '高频' },
    { word: 'sequence', phonetic: '/ˈsiːkwəns/', meaning: 'n. 顺序', example: 'Follow the sequence of events.', category: '中频' },
    { word: 'series', phonetic: '/ˈsɪriːz/', meaning: 'n. 系列', example: 'A series of lectures.', category: '高频' },
    { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: 'adj. 重要的', example: 'This is a significant discovery.', category: '高频' },
    { word: 'similar', phonetic: '/ˈsɪmələr/', meaning: 'adj. 相似的', example: 'The two are very similar.', category: '高频' },
    { word: 'simulate', phonetic: '/ˈsɪmjuleɪt/', meaning: 'v. 模拟', example: 'The program simulates flight.', category: '中频' },
    { word: 'society', phonetic: '/səˈsaɪəti/', meaning: 'n. 社会', example: 'Society is constantly changing.', category: '高频' },
    { word: 'solution', phonetic: '/səˈluːʃn/', meaning: 'n. 解决方案', example: 'Find a solution to the problem.', category: '高频' },
    { word: 'source', phonetic: '/sɔːrs/', meaning: 'n. 来源', example: 'The source of the river is in the mountains.', category: '高频' },
    { word: 'specific', phonetic: '/spəˈsɪfɪk/', meaning: 'adj. 具体的', example: 'Give specific examples.', category: '高频' },
    { word: 'stability', phonetic: '/stəˈbɪləti/', meaning: 'n. 稳定', example: 'Economic stability is important.', category: '中频' },
    { word: 'standard', phonetic: '/ˈstændərd/', meaning: 'n. 标准; adj. 标准的', example: 'Set high standards.', category: '高频' },
    { word: 'status', phonetic: '/ˈsteɪtəs/', meaning: 'n. 地位；状态', example: 'Social status matters to some.', category: '高频' },
    { word: 'strategy', phonetic: '/ˈstrætədʒi/', meaning: 'n. 策略', example: 'Develop a marketing strategy.', category: '高频' },
    { word: 'structure', phonetic: '/ˈstrʌktʃər/', meaning: 'n. 结构', example: 'The building has a modern structure.', category: '高频' },
    { word: 'struggle', phonetic: '/ˈstrʌɡl/', meaning: 'v./n. 奋斗；挣扎', example: 'The struggle for freedom continues.', category: '中频' },
    { word: 'subsequent', phonetic: '/ˈsʌbsɪkwənt/', meaning: 'adj. 随后的', example: 'Subsequent events proved him right.', category: '中频' },
    { word: 'substance', phonetic: '/ˈsʌbstəns/', meaning: 'n. 物质；实质', example: 'The substance is toxic.', category: '中频' },
    { word: 'substitute', phonetic: '/ˈsʌbstɪtuːt/', meaning: 'v./n. 替代', example: 'Substitute honey for sugar.', category: '中频' },
    { word: 'sufficient', phonetic: '/səˈfɪʃnt/', meaning: 'adj. 足够的', example: 'We have sufficient evidence.', category: '高频' },
    { word: 'suggest', phonetic: '/səˈdʒest/', meaning: 'v. 建议；暗示', example: 'I suggest we leave now.', category: '高频' },
    { word: 'summary', phonetic: '/ˈsʌməri/', meaning: 'n. 摘要', example: 'Write a summary of the article.', category: '中频' },
    { word: 'supply', phonetic: '/səˈplaɪ/', meaning: 'v./n. 供应', example: 'Supply and demand determine prices.', category: '高频' },
    { word: 'support', phonetic: '/səˈpɔːrt/', meaning: 'v./n. 支持', example: 'Thank you for your support.', category: '高频' },
    { word: 'suppose', phonetic: '/səˈpoʊz/', meaning: 'v. 假设；认为', example: 'I suppose you are right.', category: '高频' },
    { word: 'survey', phonetic: '/ˈsɜːrveɪ/', meaning: 'n./v. 调查', example: 'Conduct a survey.', category: '中频' },
    { word: 'survive', phonetic: '/sərˈvaɪv/', meaning: 'v. 幸存', example: 'Only a few survived the crash.', category: '高频' },
    { word: 'suspect', phonetic: '/səˈspekt/', meaning: 'v. 怀疑', example: 'I suspect he is lying.', category: '中频' },
    { word: 'sustain', phonetic: '/səˈsteɪn/', meaning: 'v. 维持', example: 'Sustain economic growth.', category: '中频' },
    { word: 'symbol', phonetic: '/ˈsɪmbl/', meaning: 'n. 象征', example: 'The dove is a symbol of peace.', category: '中频' },
    { word: 'target', phonetic: '/ˈtɑːrɡɪt/', meaning: 'n. 目标; v. 瞄准', example: 'Set a realistic target.', category: '高频' },
    { word: 'technique', phonetic: '/tekˈniːk/', meaning: 'n. 技术；技巧', example: 'Master the technique first.', category: '高频' },
    { word: 'technology', phonetic: '/tekˈnɑːlədʒi/', meaning: 'n. 技术', example: 'Technology transforms our lives.', category: '高频' },
    { word: 'temporary', phonetic: '/ˈtempəreri/', meaning: 'adj. 暂时的', example: 'This is a temporary solution.', category: '中频' },
    { word: 'tend', phonetic: '/tend/', meaning: 'v. 倾向于', example: 'People tend to agree.', category: '高频' },
    { word: 'terminal', phonetic: '/ˈtɜːrmɪnl/', meaning: 'adj. 末期的; n. 终端', example: 'The disease is terminal.', category: '中频' },
    { word: 'territory', phonetic: '/ˈterətɔːri/', meaning: 'n. 领土；领域', example: 'Explore new territory.', category: '中频' },
    { word: 'theory', phonetic: '/ˈθɪri/', meaning: 'n. 理论', example: 'The theory is well-supported.', category: '高频' },
    { word: 'therefore', phonetic: '/ˈðerfɔːr/', meaning: 'adv. 因此', example: 'I think; therefore I am.', category: '高频' },
    { word: 'thorough', phonetic: '/ˈθɜːroʊ/', meaning: 'adj. 彻底的', example: 'Conduct a thorough investigation.', category: '中频' },
    { word: 'threat', phonetic: '/θret/', meaning: 'n. 威胁', example: 'The threat of war loomed.', category: '中频' },
    { word: 'tolerance', phonetic: '/ˈtɑːlərəns/', meaning: 'n. 容忍', example: 'Show tolerance towards others.', category: '中频' },
    { word: 'tradition', phonetic: '/trəˈdɪʃn/', meaning: 'n. 传统', example: 'Respect local traditions.', category: '高频' },
    { word: 'transfer', phonetic: '/trænsˈfɜːr/', meaning: 'v. 转移', example: 'Transfer the files to a new folder.', category: '中频' },
    { word: 'transform', phonetic: '/trænsˈfɔːrm/', meaning: 'v. 转变', example: 'Education transforms lives.', category: '中频' },
    { word: 'trend', phonetic: '/trend/', meaning: 'n. 趋势', example: 'Follow the latest trends.', category: '高频' },
    { word: 'typical', phonetic: '/ˈtɪpɪkl/', meaning: 'adj. 典型的', example: 'This is a typical example.', category: '高频' },
    { word: 'ultimate', phonetic: '/ˈʌltɪmət/', meaning: 'adj. 最终的', example: 'The ultimate goal is peace.', category: '中频' },
    { word: 'undergo', phonetic: '/ˌʌndərˈɡoʊ/', meaning: 'v. 经历', example: 'The city underwent great changes.', category: '中频' },
    { word: 'undertake', phonetic: '/ˌʌndərˈteɪk/', meaning: 'v. 承担；从事', example: 'She undertook the project.', category: '中频' },
    { word: 'unique', phonetic: '/juˈniːk/', meaning: 'adj. 独特的', example: 'Each person is unique.', category: '高频' },
    { word: 'universal', phonetic: '/ˌjuːnɪˈvɜːrsl/', meaning: 'adj. 普遍的', example: 'Universal values exist.', category: '中频' },
    { word: 'urban', phonetic: '/ˈɜːrbən/', meaning: 'adj. 城市的', example: 'Urban areas are growing.', category: '中频' },
    { word: 'urge', phonetic: '/ɜːrdʒ/', meaning: 'v. 敦促', example: 'I urge you to reconsider.', category: '中频' },
    { word: 'utilize', phonetic: '/ˈjuːtəlaɪz/', meaning: 'v. 利用', example: 'Utilize available resources.', category: '中频' },
    { word: 'valid', phonetic: '/ˈvælɪd/', meaning: 'adj. 有效的', example: 'The ticket is valid for a week.', category: '中频' },
    { word: 'value', phonetic: '/ˈvæljuː/', meaning: 'n. 价值; v. 重视', example: 'Family values are important.', category: '高频' },
    { word: 'variety', phonetic: '/vəˈraɪəti/', meaning: 'n. 多样性', example: 'A variety of options.', category: '高频' },
    { word: 'version', phonetic: '/ˈvɜːrʒn/', meaning: 'n. 版本', example: 'The latest version is better.', category: '高频' },
    { word: 'victim', phonetic: '/ˈvɪktɪm/', meaning: 'n. 受害者', example: 'The victims of the disaster.', category: '中频' },
    { word: 'violence', phonetic: '/ˈvaɪələns/', meaning: 'n. 暴力', example: 'Violence is never the answer.', category: '中频' },
    { word: 'visible', phonetic: '/ˈvɪzəbl/', meaning: 'adj. 可见的', example: 'The star is visible at night.', category: '中频' },
    { word: 'vision', phonetic: '/ˈvɪʒn/', meaning: 'n. 愿景；视力', example: 'She has a clear vision for the company.', category: '中频' },
    { word: 'vital', phonetic: '/ˈvaɪtl/', meaning: 'adj. 至关重要的', example: 'Exercise is vital for health.', category: '高频' },
    { word: 'volume', phonetic: '/ˈvɑːljuːm/', meaning: 'n. 音量；卷', example: 'Turn up the volume.', category: '中频' },
    { word: 'voluntary', phonetic: '/ˈvɑːlənteri/', meaning: 'adj. 自愿的', example: 'Voluntary work is rewarding.', category: '中频' },
    { word: 'welfare', phonetic: '/ˈwelfer/', meaning: 'n. 福利', example: 'Social welfare programs help the poor.', category: '中频' },
    { word: 'widespread', phonetic: '/ˈwaɪdspred/', meaning: 'adj. 广泛的', example: 'The practice is widespread.', category: '中频' },
    { word: 'witness', phonetic: '/ˈwɪtnəs/', meaning: 'n. 证人; v. 目睹', example: 'He witnessed the accident.', category: '中频' },
    { word: 'yield', phonetic: '/jiːld/', meaning: 'v. 产生；屈服', example: 'The investment yielded good returns.', category: '中频' },
];

const knowledgePoints = [
    { module: '语法', title: '定语从句', content: '定语从句是指在复合句中修饰名词或代词的从句。先行词是被修饰的名词或代词，关系代词或关系副词在从句中充当成分。常见的关系代词有：which, that, who, whom, whose等。' },
    { module: '语法', title: '非谓语动词', content: '非谓语动词包括不定式（to do）、动名词（doing）和分词（现在分词doing，过去分词done）。它们在句中不能独立作谓语，但可以充当主语、宾语、表语、定语、状语等成分。' },
    { module: '语法', title: '虚拟语气', content: '虚拟语气用来表示说话人的假设、愿望、建议或推测。与现在事实相反：if+过去式(were)，主句+would+do。与过去事实相反：if+had done，主句+would+have done。' },
    { module: '语法', title: '名词性从句', content: '名词性从句包括主语从句、宾语从句、表语从句和同位语从句。由that, whether, what, who, whom, whose, which, when, where, why, how等引导，在句中起名词作用。' },
    { module: '语法', title: '状语从句', content: '状语从句在句中作状语，可修饰主句中的动词、形容词、副词或整个句子。包括时间、地点、原因、目的、结果、条件、让步、比较、方式九种。' },
    { module: '语法', title: '倒装句', content: '倒装分为完全倒装和部分倒装。完全倒装将谓语动词全部置于主语前，常见于here, there, now, then等副词开头的句子。部分倒装只将助动词、情态动词或be动词提至主语前。' },
    { module: '语法', title: '强调句型', content: 'It is/was + 被强调部分 + that/who + 其他部分。可以强调主语、宾语、状语等成分，但不能强调谓语动词。强调人时可用who替代that。' },
    { module: '语法', title: '主谓一致', content: '主谓一致遵循语法一致、意义一致和就近原则。包括：单数主语用单数谓语；集合名词视情况而定；either...or等连接的主语采用就近原则。' },
    { module: '语法', title: '独立主格结构', content: '独立主格结构由名词/代词+分词/不定式/形容词/副词/介词短语构成，在句中作状语。与主句之间有逗号隔开，逻辑主语与主句主语不同。' },
    { module: '语法', title: '并列结构', content: '并列结构使用and, but, or, yet, so等并列连词连接两个或多个对等的语法单位，包括词、短语或从句。注意并列成分必须在语法形式上保持对等。' },
    { module: '词根词缀', title: 'ab-前缀', content: 'ab-表示"离开，去"：abduct（诱拐），abnormal（异常的），abuse（滥用），absorb（吸收），abstract（抽象的）。' },
    { module: '词根词缀', title: 'ad-前缀', content: 'ad-表示"向，加强"：adapt（适应），adjust（调整），adopt（采用），advance（前进），advantage（优势）。' },
    { module: '词根词缀', title: 'con-/com-前缀', content: 'con-/com-表示"共同，一起"：combine（结合），communicate（交流），community（社区），compare（比较），compete（竞争）。' },
    { module: '词根词缀', title: 'de-前缀', content: 'de-表示"向下，去除"：decline（下降），decrease（减少），defeat（击败），defend（防御），define（定义）。' },
    { module: '词根词缀', title: 'ex-前缀', content: 'ex-表示"向外，前"：examine（检查），exceed（超过），exchange（交换），exclude（排除），expand（扩展）。' },
    { module: '词根词缀', title: 'in-/im-前缀', content: 'in-/im-表示"向内，不"：include（包括），increase（增加），indicate（表明），influence（影响），improve（改善）。' },
    { module: '词根词缀', title: 'pre-前缀', content: 'pre-表示"在前，预先"：predict（预测），prefer（偏好），prepare（准备），preserve（保护），prevent（防止）。' },
    { module: '词根词缀', title: 're-前缀', content: 're-表示"再次，回"：react（反应），realize（意识到），recognize（认出），reduce（减少），refer（参考）。' },
    { module: '词根词缀', title: 'trans-前缀', content: 'trans-表示"跨越，转变"：transfer（转移），transform（转变），translate（翻译），transport（运输），transparent（透明的）。' },
    { module: '词根词缀', title: '-tion/-sion后缀', content: '-tion/-sion构成名词，表示"行为、状态、结果"：education（教育），information（信息），decision（决定），discussion（讨论），attention（注意）。' },
    { module: '词根词缀', title: 'spect词根', content: 'spect表示"看"：inspect（检查），respect（尊重），prospect（前景），spectacle（景象），spectator（观众），perspective（视角），retrospect（回顾）。' },
    { module: '词根词缀', title: 'duct词根', content: 'duct表示"引导"：conduct（引导，实施），introduce（介绍），produce（生产），reduce（减少），deduce（推断），induce（诱导）。' },
    { module: '词根词缀', title: 'struct词根', content: 'struct表示"建造"：construct（建造），structure（结构），destroy（破坏），instruct（指导），obstruct（阻碍）。' },
    { module: '词根词缀', title: 'port词根', content: 'port表示"携带，运送"：export（出口），import（进口），transport（运输），portable（便携的），report（报告），support（支持）。' },
    { module: '词根词缀', title: 'dict词根', content: 'dict表示"说"：dictate（口述），predict（预测），contradict（反驳），verdict（裁决），dictionary（词典），indicate（表明）。' },
    { module: '词根词缀', title: 'mit/miss词根', content: 'mit/miss表示"发送"：admit（承认），commit（承诺），permit（允许），submit（提交），transmit（传输），mission（使命），missile（导弹）。' },
    { module: '翻译', title: '英译中基本技巧', content: '1. 词义选择：根据语境确定词义\n2. 词类转换：英语名词可译成汉语动词\n3. 增词与减词：根据汉语表达习惯增减词语\n4. 语序调整：英语语序与汉语不同\n5. 被动语态处理：英语被动译成汉语主动' },
    { module: '翻译', title: '长句拆分法', content: '1. 先找主谓宾，确定句子主干\n2. 识别从句和修饰成分\n3. 将长句拆分为短句\n4. 按汉语表达习惯重新排列\n5. 注意逻辑关系词的处理' },
    { module: '翻译', title: '考研翻译高频考点', content: '1. 定语从句的翻译（前置/后置）\n2. 被动语态的处理\n3. 代词指代的明确化\n4. 抽象名词的具体化\n5. 插入语的处理\n6. 比较结构的翻译' },
    { module: '写作', title: '图表作文模板', content: '第一段：As is vividly illustrated in the chart/table, there has been a dramatic increase/decrease in the number of ___ from ___ to ___.\n第二段：Several factors contribute to this phenomenon. First and foremost, ___. Moreover, ___. Last but not least, ___.\n第三段：In my opinion, ___. Taking all factors into consideration, we may reasonably conclude that ___.' },
    { module: '写作', title: '议论文万能结构', content: '第一段（引出话题）：The issue of ___ has sparked a heated debate in recent years.\n第二段（正方观点）：Proponents argue that ___.\n第三段（反方观点）：Opponents, however, contend that ___.\n第四段（个人观点）：From my perspective, ___.' },
    { module: '写作', title: '建议信模板', content: 'Dear ___,\n\nI am writing to offer some suggestions regarding ___. First and foremost, it would be advisable to ___. Furthermore, you might consider ___. Last but not least, ___.\n\nI hope you will find these suggestions helpful.\n\nYours sincerely,\n___' },
    { module: '写作', title: '考研作文高分句型', content: '1. 引出观点：It is universally acknowledged that...\n2. 表示原因：There are several reasons for this phenomenon.\n3. 举例论证：A case in point is...\n4. 表示转折：Nevertheless, it should be noted that...\n5. 总结归纳：To sum up, it is imperative that...' },
    { module: '阅读', title: '主旨大意题', content: '题型特征：What is the main idea? / The passage is mainly about...\n解题技巧：\n1. 首段+尾段法：首段引出主题，尾段总结观点\n2. 主题句叠加：各段首句串联提炼主旨\n3. 高频词法：反复出现的关键词指向主题\n干扰项特征：以偏概全、过度推断、无中生有、正反混淆' },
    { module: '阅读', title: '细节理解题', content: '题型特征：According to the passage... / What do we learn about...\n解题步骤：\n1. 定位关键词（专有名词、数字、时间）\n2. 精读定位句及其前后句\n3. 同义替换匹配（正确答案往往是原文的同义改写）\n注意：过于绝对的选项通常为干扰项' },
    { module: '阅读', title: '推理判断题', content: '题型特征：It can be inferred... / What does the author imply...\n解题原则：\n1. 有据可循：推理必须基于原文\n2. 适度推理：只能推一步，不能过度\n3. 排除绝对：must, never, always等绝对词通常不选\n4. 区分事实与观点：推理题考察的是隐含信息而非明示信息' },
    { module: '阅读', title: '词义猜测题', content: '解题方法：\n1. 上下文语境法：利用前后解释、举例、同位语推断\n2. 逻辑关系法：转折(but)、因果(because)、并列(and)等\n3. 构词法：利用词根词缀拆分单词\n4. 指代关系：it, they, this, that等的指代对象\n常见错误：脱离语境直接判断，或仅根据字面意思猜测' },
    { module: '阅读', title: '态度观点题', content: '常见态度词汇：\n正面：supportive, positive, favorable, optimistic\n负面：critical, negative, doubtful, skeptical, pessimistic\n客观：objective, neutral, impartial\n干扰：indifferent, confused, ambiguous（通常不选）\n解题关键：关注形容词、副词和情态动词的情感色彩' },
];

const questions = [
    {
        category: '阅读理解',
        passage: 'The history of cinema is a fascinating journey through technological innovation and artistic expression. From the Lumière brothers\' first public screening in 1895 to today\'s digital blockbusters, film has evolved dramatically.',
        question_text: 'When did the Lumière brothers hold their first public screening?',
        options: JSON.stringify(['A. 1890', 'B. 1895', 'C. 1900', 'D. 1905']),
        answer: 'B',
        explanation: 'The passage clearly states that the Lumière brothers held their first public screening in 1895.',
        keywords: JSON.stringify(['cinema', 'Lumière', 'screening']),
        difficulty: 'easy'
    },
    {
        category: '阅读理解',
        passage: 'Climate change is one of the most pressing issues of our time. The scientific consensus is clear: human activities are fundamentally altering the Earth\'s climate system.',
        question_text: 'What is the main idea of the passage?',
        options: JSON.stringify(['A. Climate change is not a serious issue', 'B. The Earth\'s climate is changing naturally', 'C. Climate change is a pressing issue caused by human activities', 'D. Scientists disagree about climate change']),
        answer: 'C',
        explanation: 'The passage states that climate change is a pressing issue and that human activities are altering the climate system.',
        keywords: JSON.stringify(['climate', 'change', 'human', 'activities']),
        difficulty: 'medium'
    },
    {
        category: '阅读理解',
        passage: 'Artificial intelligence has made remarkable progress in recent years. From autonomous vehicles to medical diagnosis, AI systems are increasingly capable of performing tasks that once required human intelligence. However, concerns about job displacement and ethical implications continue to spark debate.',
        question_text: 'What concern about AI is mentioned in the passage?',
        options: JSON.stringify(['A. AI is not making enough progress', 'B. AI is too expensive to develop', 'C. AI may cause job displacement', 'D. AI cannot perform complex tasks']),
        answer: 'C',
        explanation: 'The passage mentions "concerns about job displacement" as one of the ongoing debates surrounding AI development.',
        keywords: JSON.stringify(['artificial intelligence', 'job displacement', 'ethical']),
        difficulty: 'medium'
    },
    {
        category: '阅读理解',
        passage: 'The relationship between sleep and memory has been extensively studied. Research shows that during sleep, the brain consolidates memories, transferring information from short-term to long-term storage. This process is crucial for learning and academic performance.',
        question_text: 'According to the passage, what happens to memories during sleep?',
        options: JSON.stringify(['A. They are created for the first time', 'B. They are erased to make room', 'C. They are consolidated from short-term to long-term storage', 'D. They are transferred to other people']),
        answer: 'C',
        explanation: 'The passage states that during sleep, "the brain consolidates memories, transferring information from short-term to long-term storage."',
        keywords: JSON.stringify(['sleep', 'memory', 'consolidation']),
        difficulty: 'easy'
    },
    {
        category: '阅读理解',
        passage: 'Globalization has transformed the world economy over the past half century. International trade has grown exponentially, and cross-border investment has become commonplace. While globalization has lifted millions out of poverty, critics argue that it has also increased inequality within countries.',
        question_text: 'What criticism of globalization is mentioned?',
        options: JSON.stringify(['A. It has reduced international trade', 'B. It has increased inequality within countries', 'C. It has decreased cross-border investment', 'D. It has eliminated poverty completely']),
        answer: 'B',
        explanation: 'The passage notes that "critics argue that it has also increased inequality within countries."',
        keywords: JSON.stringify(['globalization', 'inequality', 'international trade']),
        difficulty: 'medium'
    },
    {
        category: '完形填空',
        passage: 'The internet has ___1___ the way we communicate. Before its widespread adoption, people relied on letters and telephone calls. Today, email and social media platforms have become the ___2___ means of communication for many people.',
        question_text: '1. What word best fits in blank 1?',
        options: JSON.stringify(['A. destroyed', 'B. transformed', 'C. ignored', 'D. prevented']),
        answer: 'B',
        explanation: '"Transformed" best fits the context, describing how the internet fundamentally changed communication.',
        keywords: JSON.stringify(['internet', 'communication', 'transform']),
        difficulty: 'easy'
    },
    {
        category: '完形填空',
        passage: 'The internet has transformed the way we communicate. Before its widespread adoption, people relied on letters and telephone calls. Today, email and social media platforms have become the ___2___ means of communication for many people.',
        question_text: '2. What word best fits in blank 2?',
        options: JSON.stringify(['A. least', 'B. worst', 'C. dominant', 'D. rare']),
        answer: 'C',
        explanation: '"Dominant" means most important or influential, which accurately describes the role of email and social media in modern communication.',
        keywords: JSON.stringify(['communication', 'dominant', 'email', 'social media']),
        difficulty: 'medium'
    },
    {
        category: '完形填空',
        passage: 'Regular exercise offers numerous health benefits. It strengthens the heart, improves blood circulation, and helps maintain a healthy weight. ___3___, exercise can boost mental health by reducing stress and anxiety.',
        question_text: '3. What word best fits in blank 3?',
        options: JSON.stringify(['A. However', 'B. Moreover', 'C. Therefore', 'D. Nevertheless']),
        answer: 'B',
        explanation: '"Moreover" adds an additional benefit of exercise (mental health) to the previously mentioned physical benefits.',
        keywords: JSON.stringify(['exercise', 'health', 'mental health']),
        difficulty: 'easy'
    },
    {
        category: '完形填空',
        passage: 'The education system in many countries is ___4___ significant changes. Traditional classroom-based learning is being supplemented, and in some cases replaced, by online learning platforms.',
        question_text: '4. What word best fits in blank 4?',
        options: JSON.stringify(['A. resisting', 'B. undergoing', 'C. avoiding', 'D. completing']),
        answer: 'B',
        explanation: '"Undergoing" means experiencing or going through, which correctly describes the process of change in education systems.',
        keywords: JSON.stringify(['education', 'change', 'online learning']),
        difficulty: 'medium'
    },
    {
        category: '完形填空',
        passage: 'The concept of sustainable development has gained ___5___ attention in recent decades. Governments and businesses alike are recognizing the need to balance economic growth with environmental protection.',
        question_text: '5. What word best fits in blank 5?',
        options: JSON.stringify(['A. decreasing', 'B. negligible', 'C. increasing', 'D. minimal']),
        answer: 'C',
        explanation: '"Increasing" correctly indicates that sustainable development has received more attention over time.',
        keywords: JSON.stringify(['sustainable development', 'economic growth', 'environmental protection']),
        difficulty: 'easy'
    },
    {
        category: '翻译',
        passage: '',
        question_text: 'Translate the following sentence into Chinese: "The advancement of technology has brought about profound changes in every aspect of our daily lives."',
        options: null,
        answer: '技术的进步给我们日常生活的各个方面带来了深刻的变化。',
        explanation: '"Advancement"译为"进步"；"brought about"译为"带来"；"profound changes"译为"深刻的变化"；"every aspect of our daily lives"译为"我们日常生活的各个方面"。注意语序调整：英语长定语需拆分为短句。',
        keywords: JSON.stringify(['advancement', 'profound', 'aspect']),
        difficulty: 'medium'
    },
    {
        category: '翻译',
        passage: '',
        question_text: 'Translate the following sentence into Chinese: "Only through continuous learning can we keep pace with the rapidly changing world."',
        options: null,
        answer: '只有通过不断学习，我们才能跟上快速变化的世界。',
        explanation: '"Only through..."是倒装结构，译为"只有通过..."；"keep pace with"译为"跟上..."；"rapidly changing"译为"快速变化的"。注意英语倒装句在汉语中的语序调整。',
        keywords: JSON.stringify(['continuous', 'keep pace with', 'rapidly changing']),
        difficulty: 'hard'
    },
    {
        category: '翻译',
        passage: '',
        question_text: 'Translate the following sentence into Chinese: "It is generally believed that education is the key to a country\'s long-term prosperity."',
        options: null,
        answer: '人们普遍认为，教育是国家长期繁荣的关键。',
        explanation: '"It is generally believed that..."是形式主语结构，译为"人们普遍认为..."；"the key to"译为"...的关键"；"long-term prosperity"译为"长期繁荣"。',
        keywords: JSON.stringify(['generally believed', 'prosperity', 'key']),
        difficulty: 'medium'
    },
];

db.serialize(() => {
    const wordStmt = db.prepare('INSERT OR IGNORE INTO words (word, phonetic, meaning, example, category) VALUES (?, ?, ?, ?, ?)');
    words.forEach(word => { wordStmt.run(word.word, word.phonetic, word.meaning, word.example, word.category); });
    wordStmt.finalize();

    const knowledgeStmt = db.prepare('INSERT OR IGNORE INTO knowledge_points (module, title, content) VALUES (?, ?, ?)');
    knowledgePoints.forEach(kp => { knowledgeStmt.run(kp.module, kp.title, kp.content); });
    knowledgeStmt.finalize();

    const questionStmt = db.prepare('INSERT OR IGNORE INTO questions (category, passage, question_text, options, answer, explanation, keywords, difficulty) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
    questions.forEach(q => { questionStmt.run(q.category, q.passage, q.question_text, q.options, q.answer, q.explanation, q.keywords, q.difficulty); });
    questionStmt.finalize();

    console.log('样本数据导入成功！共导入 ' + words.length + ' 单词, ' + knowledgePoints.length + ' 知识点, ' + questions.length + ' 题');
    db.close();
});
